name: Test Scipy

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  scipy:
    name: Check SciPy Build and Test Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: mamba-org/setup-micromamba@v1.8.0
        with:
          environment-file: ci/environment_linux.yml
          create-args: >-
            python=3.10

      - uses: hendrikmuhs/ccache-action@main
        with:
          variant: sccache
          key: ${{ github.job }}-${{ matrix.os }}

      - name: Build Linux
        shell: bash -e -l {0}
        run: |
            ./build0.sh
            cmake . -GNinja \
              -DCMAKE_BUILD_TYPE=Debug \
              -DWITH_LLVM=yes \
              -DLFORTRAN_BUILD_ALL=yes \
              -DWITH_STACKTRACE=no \
              -DCMAKE_PREFIX_PATH="$CONDA_PREFIX" \
              -DCMAKE_INSTALL_PREFIX=`pwd`/inst \
              -DCMAKE_C_COMPILER_LAUNCHER=sccache \
              -DCMAKE_CXX_COMPILER_LAUNCHER=sccache

            cmake --build . -j16 --target install

      - name: Test SciPy
        shell: bash -e -x -l {0}
        run: |
            git clone https://github.com/scipy/scipy.git
            cd scipy
            git checkout 527f2ddcda98ebf4dae37abc38c85082218fcd6a
            find . -name "*.f" > files.txt
            files=$(<files.txt)
            for file in $files; do
                ../src/bin/lfortran --fixed-form fmt --no-color $file > $file.f90
                gfortran -fallow-argument-mismatch -ffree-line-length-none -c $file.f90 -o $file.o
                #if [[ "$file" == *"minpack"* ]]; then
                #    if [[ "$file" != *"dpmpar.f"* ]]; then
                #        ../src/bin/lfortran --show-asr --no-indent --no-color --fixed-form --implicit-typing --implicit-interface $file > $file.asr
                #    fi
                #fi

            done

            cd ..
            rm -rf scipy/
            git clone https://github.com/pranavchiku/scipy.git
            cd scipy
            git checkout -t origin/scipy1
            git checkout a70f11a305edd024cb9a0e5048257eb0f51e29e1
            find . -name "*.f" > files.txt
            files=$(<files.txt)
            for file in $files; do
                ../src/bin/lfortran --fixed-form --implicit-typing --implicit-interface --implicit-argument-casting --show-asr --no-color $file > $file.f90
            done
            cd ..
            rm -rf scipy/

      - name: Build SciPy
        shell: bash -e -x -l {0}
        run: |
            git clone https://github.com/scipy/scipy
            cd scipy
            git remote add ondrej https://github.com/certik/scipy
            git fetch ondrej
            git checkout -t ondrej/merge_special_minpack_minpack2_fitpack_integrate_01
            git checkout 503037097dad5a7d33c1445e8778a9cdf1f9ef11
            micromamba env create -f environment.yml
            micromamba activate scipy-dev
            git submodule update --init
            mkdir lfortran-build/
            cd lfortran-build/
            LIBRARY_PATH="`pwd`/../../src/runtime/"
            FC=$(pwd)/../../src/bin/lfortran cmake \
              -DCMAKE_Fortran_FLAGS=--verbose \
              -DLFORTRAN_RUNTIME_LIBRARY_PATH=$LIBRARY_PATH \
              ..
            make install
            cp ${{ github.workspace }}/src/runtime/liblfortran_runtime.*  $CONDA_PREFIX/lib
            cd ../
            python dev.py build

      - name: Test SciPy Special (Specfun, Amos, Mach and Cdflib)
        shell: bash -e -x -l {0}
        run: |
            cd scipy/
            micromamba activate scipy-dev
            python dev.py test -t scipy.special -v

      - name: Test SciPy Minpack & Minpack2
        shell: bash -e -x -l {0}
        run: |
            cd scipy/
            micromamba activate scipy-dev
            python dev.py test -t scipy.optimize -v

      - name: Test SciPy Fitpack
        shell: bash -e -x -l {0}
        run: |
            cd scipy/
            micromamba activate scipy-dev
            python dev.py test -t scipy.interpolate -v

      - name: Test SciPy Mach & Quadpack (Integrate)
        shell: bash -e -x -l {0}
        run: |
            cd scipy/
            micromamba activate scipy-dev
            python dev.py test -t scipy.integrate -v
